Module 1/ Portfolio project: Setup and Mobile First
78fatemanazari/My-Portfolio pull request #1
Opened 2023-05-31 20:03 UTC by 78fatemanazari

Description: 

I created these sections:

- The header section with the menu icon and an image
- The headline section with heading and paragraphs to introduce myself 
- A button to start collaboration
- An image at the bottom of the headline section 

I used:

- Semantic HTML tags & CSS rules
- Flexbox to layout my header and headline
- responsive values in my CSS rules
- Figma design

This project is a mobile-first portfolio, part 1.

2023-05-31 21:01 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @78fatemanazari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 06:10 UTC, emmiiorji requested changes
Hi @78fatemanazari, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871494-508d17d2-994a-4882-9dbe-dc118efcad37.gif'/>
</div>

 ## Good Highlights✔️

- Background image used to represent non-content design
- Good documentation in readme

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 06:10 UTC, emmiiorji commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_1.svg");
You have done great by adding the background image as requested by the previous reviewer. However, the path specified for the image seems not to be correctly relative to the main.css file. The path needs to be correct to be recognized when hosted online.

In relation to the location of the style.css file, the path to the image would be `./images/image_geometry_1.svg` instead of `/stylesheets/images/image_geometry_1.svg`. Kindly modify it to the correct relative path.

Display on sample online server:
| With `./images/image_geometry_1.svg`     | With `/stylesheets/images/image_geometry_1.svg`      |
| ------------- | ------------- |
| ![image](https://github.com/78fatemanazari/My-Portfolio/assets/20554583/36224cb0-a9e8-49c8-9123-f13f9bfe6fba) | ![image](https://github.com/78fatemanazari/My-Portfolio/assets/20554583/b908296a-98d6-4eb5-8de1-4c2624aca1c3)|

2023-06-01 06:10 UTC, emmiiorji commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_2.svg");
As mentioned above, kindly correct the path to the image.

2023-06-01 06:17 UTC, emmiiorji commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_1.svg");
A look at the figma design shows that there's no margin between the background image and the edge of the page. Kindly adjust yours to match.

| Your design     | Figma design      |
| ------------- | ------------- |
| ![image](https://github.com/78fatemanazari/My-Portfolio/assets/20554583/b739a864-2dc6-4bd3-852d-47e64523aa48) | ![image](https://github.com/78fatemanazari/My-Portfolio/assets/20554583/5632b495-41c5-4afa-a488-6b8d3d4a3e08)|

2023-06-01 06:32 UTC, 78fatemanazari commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_1.svg");
Please give me more information. I stuck to what to do.
@emmiiorji

2023-06-01 07:12 UTC, emmiiorji commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_1.svg");
Hi @78fatemanazari

I've updated the illustration image.

2023-06-01 07:49 UTC, 78fatemanazari commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_1.svg");
![Capture](https://github.com/78fatemanazari/My-Portfolio/assets/119149574/5673fecf-c541-4299-9b02-1eca8a501932)

Sir
The width of my container is 318px according to Figma design, but I did not add any left margin to elements, and there is no margin if I don't say wrong.
@emmiiorji

2023-06-01 08:09 UTC, emmiiorji commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_1.svg");
Hi @78fatemanazari,

Apologies, I seemed to have taken the screenshot on a different width. Kindly ignore this comment.

2023-06-01 08:17 UTC, 78fatemanazari commented on stylesheets/main.css
> +  background-image: url("/stylesheets/images/image_geometry_1.svg");
No problem Sir, thank you so much for your answers.

2023-06-01 08:37 UTC, wayungi approved these changes
Hi @78fatemanazari , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] Readme is well documented ✔️ 
- [ ] All requested changes have been implemented ✔️ 
- [ ]  Correct GitHub flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 08:44 UTC, merged