Module 1/ Portfolio: Desktop Version
78fatemanazari/My-Portfolio pull request #6
Opened 2023-06-08 22:40 UTC by 78fatemanazari

Description:
I created the desktop version of my portfolio.
I used media query, grid, flexbox, and positioning.
I cared about responsive design and UX.

2023-06-08 22:46 UTC, 78fatemanazari commented
Dear code reviewer, I hope you are doing well.
I want to explain something about my project.
My project is complex, and I tried a lot to build it similar to the Figma design. 
Please understand me and besides your comments guide me on how I can solve those problems. Thank you so much.

2023-06-09 00:15 UTC, braincee requested changes
Hello @78fatemanazari 👋 , I am @braincee your Code Reviewer

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/78104544/225492039-ed22bba9-481a-489f-ae04-74623970af20.gif)

HIGHLIGHTS
------

- Great implementation of _FIGMA DESIGN_. 👍 

REQUIRED CHANGES ♻️
------
**_Please check the comments under the review._**

OPTIONAL CHANGES
--------
**_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @braincee in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

----

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 00:15 UTC, braincee commented on index.html
>  <footer class="footer">
- [ ] Please I highly suggest sticking to the required [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=23-9&t=PkaVLIZXpsHgbtYV-0)

_**REQUIRED FIGAM DESIGN**_

![Screenshot (330)](https://github.com/78fatemanazari/My-Portfolio/assets/78104544/fdd14d80-e0f2-4a31-9a94-2e9c66a393d1)


_**YOUR DESIGN**_

- [ ] Please I highly suggest implementing the desktop minimum breakpoint `min-width: 768px` to the `footer` section to fit the required Figma design. 

![Screenshot (331)](https://github.com/78fatemanazari/My-Portfolio/assets/78104544/775e6043-7481-420a-9e36-94be38d4bbd0)

2023-06-09 06:17 UTC, 78fatemanazari commented on index.html
> +                  <a href="/"><button class="btn-two" type="submit">Get my CV<img src="stylesheets/images/ic_download.svg" alt="ic download img"></button></a>
Dera code reviewer!
I can not give the get my cv button an effect because the main problem is the image, I can not change the color of the image. Do you have any suggestions? 
![Capture](https://github.com/78fatemanazari/My-Portfolio/assets/119149574/b81ed1dc-ffc8-4fda-8627-fddd87376e67)
@braincee

2023-06-09 09:39 UTC, shahadat3669 requested changes
Hi @78fatemanazari , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 09:39 UTC, shahadat3669 commented on index.html
> +<div class="link"><a href="/">Get my Resume <img src="stylesheets/images/ic_link_teal.svg" alt="ic link teal img"></a></div>
Hi! I noticed that as the previous reviewer requested, you updated your resume button, but I noticed that the button doesn't have an icon when hovered over. I saw your comment stating that you attempted to add one but were unsuccessful. One possible solution could be to use two icons: one white and one dark. By default, you would show the white icon and hide the dark one. However, when the button is hovered over, you can hide the white icon and show the dark one instead. This approach would allow you to achieve the desired design. This is just one suggestion, and if you have any other ideas or a better approach, feel free to try them out.

![image](https://github.com/78fatemanazari/My-Portfolio/assets/55840999/2cde4307-6af9-44f7-8946-cac54b575157)

2023-06-09 09:39 UTC, shahadat3669 commented on index.html
> +                  <button class="btn-two" type="submit"><a href="/">Get my CV<img src="stylesheets/images/ic_download.svg" alt="ic download img"></a></button>
Hi! I noticed that as the previous reviewer requested, you updated your resume button, but I noticed that the button doesn't have an icon when hovered over. I saw your comment stating that you attempted to add one but were unsuccessful. One possible solution could be to use two icons: one white and one dark. By default, you would show the white icon and hide the dark one. However, when the button is hovered over, you can hide the white icon and show the dark one instead. This approach would allow you to achieve the desired design. This is just one suggestion, and if you have any other ideas or a better approach, feel free to try them out.

![image](https://github.com/78fatemanazari/My-Portfolio/assets/55840999/2cde4307-6af9-44f7-8946-cac54b575157)

2023-06-09 09:39 UTC, shahadat3669 commented on index.html
>  <footer class="footer">
As per the previous reviewer's request, please make sure to update the footer section. However, during my review of your project, I noticed that many elements have fixed pixel widths and heights. This is causing the footer to appear distorted on different screen sizes. I strongly suggest considering the use of percentage values instead of pixels to ensure a more responsive and visually appealing footer across various screen sizes. 👍

2023-06-09 15:01 UTC, amon-cofie approved these changes
Hi @78fatemanazari , 👋 

Your project is complete 💯!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights

🚀 You implemented the changes that the previous reviewer requested 
🚀 You have good and descriptive commit messages
🚀 You used GitHub flow properly
🚀 You have no linter errors


## Optional suggestions

- [ ] Although you made all the changes that the previous reviewers requested, there is one thing I would like to draw your attention to regarding units in CSS and in-line with the previous reviewer's last comment. I noticed a lot of inconsistencies in the way you use the units especially when defining widths and heights. Just like the previous reviewer mentioned, I strongly suggest that you try as much as you can to use the relative units more than the fixed units. Check the inline comments below for one reason why this is bad.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 15:01 UTC, amon-cofie commented on stylesheets/style.css
> +  }
[OPTIONAL] You can observe from here how the width, height, bottom, and left dimensions have the tendency to overflow the boundaries of their container when you do a little math because these values are fixed, resizing doesn't affect them in any way and they will remain the same no matter the screen size. Observe from the screenshot below:
![image](https://github.com/78fatemanazari/My-Portfolio/assets/107795045/c45e51af-034f-467f-9995-e428175bc3e0)

2023-06-09 15:33 UTC, merged

2023-06-15 17:13 UTC, Godedict reviewed
(optional) - I suggest you use width instead <br> to break lines. It is better for responsiveness.

https://github.com/78fatemanazari/My-Portfolio/blob/7413b93440b993683e154d5fe0ab3d14db706db8/index.html#L46-L47